---
roles:
  - name: geerlingguy.swap
    version: 2.0.0
  - name: geerlingguy.docker
    version: 8.0.0

collections:
  - name: hifis.toolkit
    version: 6.3.2
  - name: devsec.hardening
    version: 10.4.0
  - name: community.general
    version: 12.2.0
  - name: community.mysql
    version: 4.0.1
  - name: community.docker
    version: 5.0.5
