---
roles:
  - name: geerlingguy.swap
    version: 1.3.0
  - name: geerlingguy.docker
    version: 7.9.0

collections:
  - name: hifis.toolkit
    version: 6.3.1
  - name: devsec.hardening
    version: 10.4.0
  - name: community.general
    version: 12.0.1
  - name: community.mysql
    version: 4.0.1
  - name: community.docker
    version: 5.0.2
